name: Backend CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/my-backend:latest
          docker build -t $IMAGE ./infra/backend
          docker push $IMAGE

      - name: Deploy to EC2 (Blue-Green)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            IMAGE=ghcr.io/${{ github.repository_owner }}/my-backend:latest
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            if docker ps --filter "name=backend-blue" | grep backend-blue; then
                ACTIVE=blue
                INACTIVE=green
                PORT=8082
            else
                ACTIVE=green
                INACTIVE=blue
                PORT=8081
            fi

            docker pull $IMAGE
            docker stop backend-$INACTIVE || true
            docker rm backend-$INACTIVE || true
            docker run -d --name backend-$INACTIVE \
              -p $PORT:8080 \
              -e SPOTIFY_CLIENT_ID="${{ secrets.SPOTIFY_CLIENT_ID }}" \
              -e SPOTIFY_CLIENT_SECRET="${{ secrets.SPOTIFY_CLIENT_SECRET }}" \
              -e TMDB_API_KEY="${{ secrets.TMDB_API_KEY }}" \
              -e LIBRARY_API_KEY="${{ secrets.LIBRARY_API_KEY }}" \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              -e NAVER_CLIENT_ID="${{ secrets.NAVER_CLIENT_ID }}" \
              -e NAVER_CLIENT_SECRET="${{ secrets.NAVER_CLIENT_SECRET }}" \
              -e KAKAO_CLIENT_ID="${{ secrets.KAKAO_CLIENT_ID }}" \
              -e KAKAO_CLIENT_SECRET="${{ secrets.KAKAO_CLIENT_SECRET }}" \
              # 설정 해줘야함
              -e REDIS_HOST="your-redis-host" \
              -e REDIS_PORT="6379" \
              -e SPRING_DATASOURCE_URL="jdbc:mysql://your-mysql-host:3306/dbname" \
              -e SPRING_DATASOURCE_USERNAME="${{ secrets.MYSQL_USER }}" \
              -e SPRING_DATASOURCE_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
              $IMAGE

            sed -i "s/server 127.0.0.1:808[12];/server 127.0.0.1:$PORT;/g" /etc/nginx/conf.d/backend.conf
            nginx -s reload

            echo "✅ Deployment complete. Active container: $INACTIVE"
