name: Backend CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/my-backend:latest
          docker build -t $IMAGE ./backend
          docker push $IMAGE

      - name: Deploy to EC2 (Blue-Green)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            IMAGE=ghcr.io/${{ github.repository_owner }}/my-backend:latest

            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            if docker ps --filter "name=backend-blue" | grep backend-blue; then
                ACTIVE=blue
                INACTIVE=green
                PORT=8082
            else
                ACTIVE=green
                INACTIVE=blue
                PORT=8081
            fi
            
            docker pull $IMAGE
            docker stop backend-$INACTIVE || true
            docker rm backend-$INACTIVE || true
            docker run -d --name backend-$INACTIVE -p $PORT:8080 $IMAGE
            
            sed -i "s/server 127.0.0.1:808[12];/server 127.0.0.1:$PORT;/g" /etc/nginx/conf.d/backend.conf
            nginx -s reload

            echo "Deployment complete. Active container: $INACTIVE"
